name: Tag Changelog

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate Changelog
        uses: metcalfc/changelog-generator@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          output: CHANGELOG.md